### ISSUE TITLE
Todo MVP

### ISSUE THREAD

**Issue by planemad** [folography/visavis#1]
- [x] @planemad get map layer toggling to work
- [x] @planemad shows constituency stats on mouse hover on the map
- [x] @adityadipankar design and create html map legend template
- [x] @adityadipankar customize styling on index and app page
- [x] @priyankaborar get scatterplot working
- [ ] @adityadipankar update about page

**Comment by planemad** [comment]
Some base functionality is in^

Had to use my test map because i needed info on the layer names. Once i can architect the functions, we can switch back to the original map.

@adityadipankar @priyankaborar

**Comment by planemad** [comment]
Stale
